apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: collegeapp-db-statefulset
  namespace: myns
  labels:
    app: collegeapp
    tier: db
    env: dev
spec:
  selector:
    matchLabels:
      app: collegeapp
      tier: db
      env: dev
  serviceName: collegeapp-db-service
  replicas: 1
  template:
    metadata:
      labels:
        app: collegeapp
        tier: db
        env: dev
    spec:
      containers:
      - name: collegeapp-db-container
        image: postgres:12
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
          name: dbport
        envFrom:
        - secretRef:
            name: collegeapp-db-secret
        volumeMounts:
        - name: collegeapp-db-vct
          mountPath: /var/lib/postgresql/data/pgdata
  volumeClaimTemplates:
  - metadata:
      name: collegeapp-db-vct
      namespace: myns
    spec:
      storageClassName: "efs-sc"
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: collegeapp-db-secret
  namespace: myns
type: Opaque
data:
  POSTGRES_DB: bXlhcHBfZGI=
  POSTGRES_USER: YXNob2sK
  POSTGRES_PASSWORD: YXNob2sxMjM=
---
apiVersion: v1
kind: Service
metadata:
  name: collegeapp-db-service
  namespace: myns
spec:
  selector:
    app: collegeapp
    tier: db
    env: dev
  ports:
  - port: 5432
    targetPort: dbport
 
