apiVersion: apps/v1
kind: Deployment
metadata:
  name: collegeapp-db-deploymet
  labels:
    app: postgress
    project: django
    tier: db
  namespace: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgress
      project: django
      tier: db
  template:
    metadata:
      labels:
        app: postgress
        project: django
        tier: db
    spec:
      containers:
      - name: postgress
        image: postgres:12
        imagePullPolicy: Always
        env:
        - name: POSTGRES_DB
          value: myapp_db
        - name: POSTGRES_USER
          value: ashok
        - name: POSTGRES_PASSWORD
          value: ashok123
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: college-app-db-service
  namespace: django
spec:
  selector:
    app: postgress
    project: django
    tier: db 
  ports:
  - port: 5432
    targetPort: 5432
